version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    image: ${DOCKER_IMAGE}
    container_name: spring-boot-app
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis